"""phase2 trend radar

Revision ID: 2ed18121ba4f
Revises: cef1a834b170
Create Date: 2026-10-05 16:42:58.176760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed18121ba4f'
down_revision: Union[str, Sequence[str], None] = 'cef1a834b170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_relations',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', 'source')
    )
    op.create_table('keyword_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('demand', sa.Float(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('competition', sa.Float(), nullable=True),
    sa.Column('growth', sa.Float(), nullable=True),
    sa.Column('sources_rising', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id', 'date')
    )
    with op.batch_alter_table('product_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_sold_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('shop_sold_count')

    with op.batch_alter_table('product_snapshots', schema=None) as batch_op:
        batch_op.drop_column('views')

    op.drop_table('keyword_scores')
    op.drop_table('keyword_relations')
    # ### end Alembic commands ###
