"""alerts

Revision ID: 6ed06a8bb741
Revises: 61881d0eaaab
Create Date: 2026-10-07 15:12:22.342091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed06a8bb741'
down_revision: Union[str, Sequence[str], None] = '61881d0eaaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('watch_keyword', sa.String(length=200), nullable=True),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_kind_subject_created', ['kind', 'subject_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_kind_subject_created')

    op.drop_table('alerts')
    # ### end Alembic commands ###
