"""listing signals

Revision ID: f4c2cbd0e624
Revises: 2ed18121ba4f
Create Date: 2026-10-07 10:06:02.173152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c2cbd0e624'
down_revision: Union[str, Sequence[str], None] = '2ed18121ba4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_signals',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discovered_on', sa.Date(), nullable=False),
    sa.Column('discovery_query', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('delta_views', sa.Float(), nullable=True),
    sa.Column('delta_saves', sa.Float(), nullable=True),
    sa.Column('dsr', sa.Float(), nullable=True),
    sa.Column('updated_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('tags')

    op.drop_table('listing_signals')
    # ### end Alembic commands ###
